export * from './01-basic-interaction/parent.component'
export * from './02-view-encapsulation/parent.component'
export * from './03-host-bindings/host-parent.component'
export * from './04-accessing-elements-in-code/accessing-elements.component'
export * from './05-content-projection/content-projection-parent.component'
export * from './06-dynamic-component-render/dynamic-render-parent.component'